'''HTTPS://DLIB.NET/LICENSE.HTML
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
'''
#YOU NEED TO REMOVE YOUR GLASSES FOR THIS TO WORK!
import face_biometric_recognition
import sys
import face_recognition

image = face_recognition.load_image_file("D:/Github/Student-Ignite/Face-Biometric/Me3/me.jpeg")
face_locations = face_recognition.face_locations(image)
assert len(face_locations) >= 1
print(face_locations)


# face_locations is now an array listing the co-ordinates of each face!

picture_of_me = face_biometric_recognition.load_image_file('D:/Github/Student-Ignite/Face-Biometric/Me3/me.jpeg')
my_face_encoding = face_biometric_recognition.face_encodings(picture_of_me)[0]

# my_face_encoding now contains a universal 'encoding' of my facial features
# that can be compared to any other picture of a face!

#unknown_picture = face_biometric_recognition.load_image_file('D:/Github/Student-Ignite/Face-Biometric/Me3/unkown.jpeg')
unknown_picture = face_biometric_recognition.load_image_file('D:/Github/Student-Ignite/Face-Biometric/Notme/WIN_20211220_19_51_13_Pro.jpg')
unknown_face_encoding = face_biometric_recognition.face_encodings(unknown_picture)[0]

# Now we can see the two face encodings
# are of the same person with `compare_faces`!

results = face_biometric_recognition.compare_faces(
    [my_face_encoding], unknown_face_encoding
)
print(results)
assert len(results) >= 1
if results[0] == True:
    print("It's a picture of me!")
else:
    print("It's not a picture of me!")
